### PR TITLE
provide babel config for decoratorsBeforeExport

### PR DESCRIPTION
**Pull request by tbremer**
This resolves issue #81.

### CODE REVIEW

**Comment by yairhaimo** [comment]
Thanks for the PR!
I think we should have the option set to `true` in order to stay with (IMO) most common use cases.

**Comment by yairhaimo** [comment]
Thanks! 🏆

**Comment by tbremer** [comment]
Thanks for merging so quickly!

Would it be possible to get a patch release cut so Atom plugins can pull in the update?

**Comment by yairhaimo** [comment]
Published import-cost library v1.6.0 with the changes.

**Comment by tbremer** [comment]
Thanks so much!

**Pull request merged**
